/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Analysis */
        post: operations["run_analysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analysis Summary */
        get: operations["get_analysis_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Csv */
        get: operations["export_analysis_csv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anomalies/{route}/{week_of}/root-cause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anomaly Root Cause */
        get: operations["get_anomaly_root_cause"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anomalies */
        get: operations["list_anomalies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anomalies/{route}/{week_of}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anomaly Detail */
        get: operations["get_anomaly"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{route}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Route Timeline */
        get: operations["get_route_timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluation Report */
        get: operations["get_evaluation_report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Metrics */
        get: operations["get_run_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisSummaryData */
        AnalysisSummaryData: {
            /** Shipment Count */
            shipment_count: number;
            /** Route Count */
            route_count: number;
            /** Route Type Count */
            route_type_count: number;
            /** Weekly Record Count */
            weekly_record_count: number;
            /** Candidate Count */
            candidate_count: number;
            /** Justified Count */
            justified_count: number;
            /** Partially Explained Count */
            partially_explained_count: number;
            /** Unexplained Count */
            unexplained_count: number;
            /**
             * Analysis From
             * Format: date
             */
            analysis_from: string;
            /**
             * Analysis To
             * Format: date
             */
            analysis_to: string;
            /** Anomaly Threshold Percent */
            anomaly_threshold_percent: number;
            /** Explanation Mode */
            explanation_mode: string;
            /** Evaluation Status */
            evaluation_status: string;
            /** Final Csv Sha256 */
            final_csv_sha256: string;
            /** Operational Root Causes Available */
            operational_root_causes_available: number;
            run_state: components["schemas"]["RunState"];
        };
        /** AnomalyData */
        AnomalyData: {
            /** Candidate Key */
            candidate_key: string;
            /** Route */
            route: string;
            /** Route Type */
            route_type: string;
            /**
             * Week Of
             * Format: date
             */
            week_of: string;
            /** Cost Per Tonne Km */
            cost_per_tonne_km: number;
            /** Own History Baseline */
            own_history_baseline: number | null;
            /** Peer Baseline */
            peer_baseline: number | null;
            /** Vs Own History Pct */
            vs_own_history_pct: number;
            /** Vs Similar Routes Pct */
            vs_similar_routes_pct: number | null;
            /** History Weeks Used */
            history_weeks_used: number;
            /** Peer Routes Used */
            peer_routes_used: number;
            /** Own Threshold Breached */
            own_threshold_breached: boolean;
            /** Peer Threshold Breached */
            peer_threshold_breached: boolean;
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "own_history" | "peer" | "both";
            verdict: components["schemas"]["EvidenceVerdict"];
            /** Flagged */
            flagged: string;
            /** Matched Note Id */
            matched_note_id: string | null;
            /** Supporting Note Ids */
            supporting_note_ids: string[];
            /** Decision Code */
            decision_code: string;
            /** Reason */
            reason: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceSummaryData"][];
            /** Explanation Source */
            explanation_source: string;
            /** Fallback Used */
            fallback_used: boolean;
            /** Operational Root Cause Available */
            operational_root_cause_available: boolean;
        };
        /** AnomalyListData */
        AnomalyListData: {
            /** Items */
            items: components["schemas"]["AnomalyData"][];
        };
        /** ArtifactComparison */
        ArtifactComparison: {
            /** Artifact Name */
            artifact_name: string;
            /** Identical */
            identical: boolean;
            /** Hashes */
            hashes: string[];
            /** Byte Sizes */
            byte_sizes: number[];
            /** First Difference */
            first_difference?: string | null;
        };
        /** ArtifactFingerprint */
        ArtifactFingerprint: {
            /** Relative Path */
            relative_path: string;
            /** Sha256 */
            sha256: string;
            /** Byte Size */
            byte_size: number;
            /** Run Id */
            run_id?: string | null;
        };
        /** CategoryContributionData */
        CategoryContributionData: {
            /** Category */
            category: string;
            /** Current Shipment Count */
            current_shipment_count: number;
            /** Reference Shipment Count */
            reference_shipment_count: number;
            /** Reference Weeks Present */
            reference_weeks_present: number;
            /** Current Tonne Km Share */
            current_tonne_km_share: number | null;
            /** Reference Mean Tonne Km Share */
            reference_mean_tonne_km_share: number | null;
            /** Current Cost Per Tonne Km */
            current_cost_per_tonne_km: number | null;
            /** Reference Mean Cost Per Tonne Km */
            reference_mean_cost_per_tonne_km: number | null;
            /** Mix Effect */
            mix_effect: number;
            /** Rate Effect */
            rate_effect: number;
            /** Entry Effect */
            entry_effect: number;
            /** Exit Effect */
            exit_effect: number;
            /** Net Contribution */
            net_contribution: number;
            /** Absolute Effect Share Pct */
            absolute_effect_share_pct: number | null;
            direction: components["schemas"]["EffectDirection"];
            support_level: components["schemas"]["SupportLevel"];
            /** Caveats */
            caveats: string[];
        };
        /**
         * CheckStatus
         * @enum {string}
         */
        CheckStatus: "pass" | "fail" | "skip";
        /** DataEnvelope[AnalysisSummaryData] */
        DataEnvelope_AnalysisSummaryData_: {
            data: components["schemas"]["AnalysisSummaryData"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** DataEnvelope[AnomalyData] */
        DataEnvelope_AnomalyData_: {
            data: components["schemas"]["AnomalyData"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** DataEnvelope[AnomalyListData] */
        DataEnvelope_AnomalyListData_: {
            data: components["schemas"]["AnomalyListData"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** DataEnvelope[EvaluationReportData] */
        DataEnvelope_EvaluationReportData_: {
            data: components["schemas"]["EvaluationReportData"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** DataEnvelope[RootCauseData] */
        DataEnvelope_RootCauseData_: {
            data: components["schemas"]["RootCauseData"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** DataEnvelope[RouteTimelineData] */
        DataEnvelope_RouteTimelineData_: {
            data: components["schemas"]["RouteTimelineData"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** DataEnvelope[RunAnalysisData] */
        DataEnvelope_RunAnalysisData_: {
            data: components["schemas"]["RunAnalysisData"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** DataEnvelope[RunMetricsData] */
        DataEnvelope_RunMetricsData_: {
            data: components["schemas"]["RunMetricsData"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** DecompositionLensData */
        DecompositionLensData: {
            /**
             * Lens
             * @enum {string}
             */
            lens: "transporter" | "material";
            /** Target Gap */
            target_gap: number;
            /** Reconstructed Gap */
            reconstructed_gap: number;
            /** Reconstruction Error */
            reconstruction_error: number;
            /** Contributions */
            contributions: components["schemas"]["CategoryContributionData"][];
            /** Leads */
            leads: components["schemas"]["OperationalLeadData"][];
            /** Offsets */
            offsets: components["schemas"]["OperationalLeadData"][];
        };
        /**
         * EffectDirection
         * @enum {string}
         */
        EffectDirection: "increases_gap" | "offsets_gap" | "neutral";
        /** EnvironmentFingerprint */
        EnvironmentFingerprint: {
            /** Python */
            python: string;
            /** Implementation */
            implementation: string;
            /** Operating System */
            operating_system: string;
            /** Architecture */
            architecture: string;
            /** Timezone */
            timezone: string;
            /** Locale */
            locale: string;
            /** Dependency Versions */
            dependency_versions: {
                [key: string]: string;
            };
            /** Dependency Lock Sha256 */
            dependency_lock_sha256: string | null;
            /** Embedding Model */
            embedding_model: string;
            /** Embedding Revision */
            embedding_revision: string;
            /** Explanation Mode */
            explanation_mode: string;
            /** Prompt Version */
            prompt_version: string;
            /** Provider Identity */
            provider_identity: string;
            /** Git Commit */
            git_commit: string | null;
            /** Dirty Worktree */
            dirty_worktree: boolean;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Request Id */
            request_id: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** EvaluationCheck */
        EvaluationCheck: {
            /** Check Id */
            check_id: string;
            domain: components["schemas"]["EvaluationDomain"];
            /** Description */
            description: string;
            /**
             * Blocking
             * @default true
             */
            blocking: boolean;
            status: components["schemas"]["CheckStatus"];
            /** Expected */
            expected?: unknown | null;
            /** Actual */
            actual?: unknown | null;
            tolerance?: components["schemas"]["NumericTolerance"] | null;
            /**
             * Details
             * @default []
             */
            details: string[];
        };
        /**
         * EvaluationDomain
         * @enum {string}
         */
        EvaluationDomain: "input_integrity" | "weekly_analytics" | "baseline_correctness" | "candidate_detection" | "context_compilation" | "retrieval_quality" | "evidence_gate" | "explanation_grounding" | "operational_root_cause" | "output_contract" | "metamorphic_invariants" | "reproducibility";
        /** EvaluationMetric */
        EvaluationMetric: {
            /** Metric Id */
            metric_id: string;
            domain: components["schemas"]["EvaluationDomain"];
            /** Value */
            value: number;
            /** Unit */
            unit: string;
            /** Target */
            target?: number | null;
            /**
             * Target Relation
             * @enum {string}
             */
            target_relation: "eq" | "gte" | "lte" | "informational";
            /**
             * Blocking
             * @default false
             */
            blocking: boolean;
            /** Numerator */
            numerator?: number | null;
            /** Denominator */
            denominator?: number | null;
        };
        /** EvaluationReport */
        EvaluationReport: {
            /**
             * Schema Version
             * @default 1.1
             * @enum {string}
             */
            schema_version: "1.0" | "1.1";
            /**
             * Overall Status
             * @enum {string}
             */
            overall_status: "pass" | "fail";
            /** Evaluation Mode */
            evaluation_mode: string;
            /** Run Count */
            run_count: number;
            environment: components["schemas"]["EnvironmentFingerprint"];
            /** Inputs */
            inputs: components["schemas"]["FileFingerprint"][];
            /** Configuration Fingerprint */
            configuration_fingerprint: string;
            /** Checks */
            checks: components["schemas"]["EvaluationCheck"][];
            /** Metrics */
            metrics: components["schemas"]["EvaluationMetric"][];
            reproducibility: components["schemas"]["ReproducibilityResult"];
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactFingerprint"][];
        };
        /** EvaluationReportData */
        EvaluationReportData: {
            report: components["schemas"]["EvaluationReport"];
            /** Report Sha256 */
            report_sha256: string;
        };
        /** EvidenceGateResultData */
        EvidenceGateResultData: {
            /**
             * Gate
             * @enum {string}
             */
            gate: "route" | "date" | "direction" | "cost_impact" | "scope";
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "fail" | "not_applicable";
            /** Reason Code */
            reason_code: string | null;
            /** Reason */
            reason: string;
        };
        /** EvidenceSummaryData */
        EvidenceSummaryData: {
            /** Note Id */
            note_id: string;
            /** Evidence Level */
            evidence_level: string;
            /**
             * Role
             * @enum {string}
             */
            role: "primary" | "supporting" | "rejected";
            /** Rejection Codes */
            rejection_codes: string[];
            /** Original Text */
            original_text: string;
            /** Scope Type */
            scope_type: string;
            /** Applies To Routes */
            applies_to_routes: string[];
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Effective To */
            effective_to: string | null;
            /** Event Type */
            event_type: string;
            /** Impact Direction */
            impact_direction: string;
            /** Affects Transport Cost */
            affects_transport_cost: boolean | null;
            /** Magnitude Text */
            magnitude_text: string | null;
            /** Gate Results */
            gate_results: components["schemas"]["EvidenceGateResultData"][];
        };
        /**
         * EvidenceVerdict
         * @enum {string}
         */
        EvidenceVerdict: "justified" | "partially_explained" | "unexplained";
        /** FileFingerprint */
        FileFingerprint: {
            /** Relative Path */
            relative_path: string;
            /** Sha256 */
            sha256: string;
            /** Byte Size */
            byte_size: number;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Ready */
            ready: boolean;
            /** Service */
            service: string;
            /** Version */
            version: string;
            run_state: components["schemas"]["RunState"];
            /** Has Snapshot */
            has_snapshot: boolean;
            /** Snapshot Id */
            snapshot_id?: string | null;
        };
        /** LatestAttemptData */
        LatestAttemptData: {
            state: components["schemas"]["RunState"];
            /** Attempt Id */
            attempt_id: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Latest Snapshot Id */
            latest_snapshot_id: string | null;
            /** Failure Code */
            failure_code: string | null;
            /** Failure Message */
            failure_message: string | null;
            /** Previous Snapshot Available */
            previous_snapshot_available: boolean;
        };
        /** MetricComparisonData */
        MetricComparisonData: {
            metric: components["schemas"]["OperationalMetric"];
            /** Unit */
            unit: string;
            /** Current Value */
            current_value: number;
            /** Reference Mean */
            reference_mean: number;
            /** Absolute Change */
            absolute_change: number;
            /** Percentage Change */
            percentage_change: number | null;
            /** Highlighted */
            highlighted: boolean;
            /** Interpretation */
            interpretation: string;
        };
        /** NumericTolerance */
        NumericTolerance: {
            /** Relative */
            relative: number;
            /** Absolute */
            absolute: number;
        };
        /** OperationalLeadData */
        OperationalLeadData: {
            /** Category */
            category: string;
            /** Effect */
            effect: number;
            support_level: components["schemas"]["SupportLevel"];
            /** Narrative */
            narrative: string;
        };
        /**
         * OperationalMetric
         * @enum {string}
         */
        OperationalMetric: "shipment_count" | "average_load_tonnes" | "weighted_average_distance_km" | "total_quantity_tonnes" | "total_tonne_km" | "freight_cost_per_shipment" | "shipments_per_100_tonnes";
        /** PaginationMeta */
        PaginationMeta: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has More */
            has_more: boolean;
        };
        /** ReproducibilityResult */
        ReproducibilityResult: {
            /** Formal */
            formal: boolean;
            /** Run Count */
            run_count: number;
            /** Runs */
            runs: components["schemas"]["ReproducibilityRun"][];
            /** Comparisons */
            comparisons: components["schemas"]["ArtifactComparison"][];
            /** Overall Reproducible */
            overall_reproducible: boolean;
        };
        /** ReproducibilityRun */
        ReproducibilityRun: {
            /** Run Id */
            run_id: string;
            /** Exit Code */
            exit_code: number;
            /** Duration Ms */
            duration_ms: number;
            /**
             * Timed Out
             * @default false
             */
            timed_out: boolean;
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactFingerprint"][];
            /** Final Csv Rows */
            final_csv_rows?: number | null;
            /** Final Csv Columns */
            final_csv_columns?: number | null;
            /**
             * Stdout Tail
             * @default
             */
            stdout_tail: string;
            /**
             * Stderr Tail
             * @default
             */
            stderr_tail: string;
        };
        /** ResponseMeta */
        ResponseMeta: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Snapshot Id */
            snapshot_id?: string | null;
            pagination?: components["schemas"]["PaginationMeta"] | null;
        };
        /** RootCauseData */
        RootCauseData: {
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0";
            /** Candidate Key */
            candidate_key: string;
            /** Route */
            route: string;
            /** Route Type */
            route_type: string;
            /**
             * Week Of
             * Format: date
             */
            week_of: string;
            /**
             * Canonical Verdict
             * @constant
             */
            canonical_verdict: "unexplained";
            /**
             * Availability
             * @constant
             */
            availability: "available";
            /** Reference Weeks */
            reference_weeks: string[];
            /** Reference Week Count */
            reference_week_count: number;
            support_level: components["schemas"]["SupportLevel"];
            /** Current Cost Per Tonne Km */
            current_cost_per_tonne_km: number;
            /** Own History Baseline */
            own_history_baseline: number;
            /** Target Gap */
            target_gap: number;
            transporter: components["schemas"]["DecompositionLensData"];
            material: components["schemas"]["DecompositionLensData"];
            /** Operational Metrics */
            operational_metrics: components["schemas"]["MetricComparisonData"][];
            /** Caveats */
            caveats: string[];
        };
        /** RouteTimelineData */
        RouteTimelineData: {
            /** Route */
            route: string;
            /** Points */
            points: components["schemas"]["TimelinePointData"][];
        };
        /** RunAnalysisData */
        RunAnalysisData: {
            /** Attempt Id */
            attempt_id: string;
            /** Snapshot Id */
            snapshot_id: string;
            /**
             * Run State
             * @default succeeded
             * @constant
             */
            run_state: "succeeded";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            /** Duration Ms */
            duration_ms: number;
            /** Shipment Count */
            shipment_count: number;
            /** Weekly Record Count */
            weekly_record_count: number;
            /** Candidate Count */
            candidate_count: number;
            /** Justified Count */
            justified_count: number;
            /** Partially Explained Count */
            partially_explained_count: number;
            /** Unexplained Count */
            unexplained_count: number;
            /** Evaluation Status */
            evaluation_status: string;
            /** Final Csv Sha256 */
            final_csv_sha256: string;
            /** Replaced Previous Snapshot */
            replaced_previous_snapshot: boolean;
        };
        /** RunAnalysisRequest */
        RunAnalysisRequest: {
            /**
             * Explanation Mode
             * @default template
             * @enum {string}
             */
            explanation_mode: "template" | "replay" | "live";
        };
        /** RunMetricsData */
        RunMetricsData: {
            /** Stage Durations Ms */
            stage_durations_ms: {
                [key: string]: number;
            };
            /** Total Duration Ms */
            total_duration_ms: number;
            /** Row Counts */
            row_counts: {
                [key: string]: number;
            };
            /** Retrieval Hit Count */
            retrieval_hit_count: number;
            /** Explanation Request Count */
            explanation_request_count: number;
            /** Hosted Model Call Count */
            hosted_model_call_count: number;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Estimated Cost Usd */
            estimated_cost_usd: string | null;
            /** Cache Hits */
            cache_hits: number;
            /** Cache Misses */
            cache_misses: number;
            /** Fallback Count */
            fallback_count: number;
            /** Input Fingerprints */
            input_fingerprints: components["schemas"]["FileFingerprint"][];
            /** Configuration Fingerprint */
            configuration_fingerprint: string;
            /** Artifact Fingerprints */
            artifact_fingerprints: components["schemas"]["ArtifactFingerprint"][];
            latest_attempt: components["schemas"]["LatestAttemptData"];
        };
        /**
         * RunState
         * @enum {string}
         */
        RunState: "idle" | "running" | "succeeded" | "failed";
        /**
         * SupportLevel
         * @enum {string}
         */
        SupportLevel: "strong" | "moderate" | "limited" | "transition_only" | "unavailable";
        /** TimelinePointData */
        TimelinePointData: {
            /**
             * Week Of
             * Format: date
             */
            week_of: string;
            /** Route Type */
            route_type: string;
            /** Cost Per Tonne Km */
            cost_per_tonne_km: number;
            /** Own History Baseline */
            own_history_baseline: number | null;
            /** Peer Baseline */
            peer_baseline: number | null;
            /** Vs Own History Pct */
            vs_own_history_pct: number | null;
            /** Vs Similar Routes Pct */
            vs_similar_routes_pct: number | null;
            /** History Weeks Used */
            history_weeks_used: number;
            /** Peer Routes Used */
            peer_routes_used: number;
            /** Candidate */
            candidate: boolean;
            verdict: components["schemas"]["EvidenceVerdict"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    run_analysis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_RunAnalysisData_"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Analysis unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_analysis_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_AnalysisSummaryData_"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Analysis unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    export_analysis_csv: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/csv": unknown;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Analysis unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_anomaly_root_cause: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                route: string;
                week_of: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_RootCauseData_"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Analysis unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_anomalies: {
        parameters: {
            query?: {
                route?: string | null;
                route_type?: string | null;
                verdict?: components["schemas"]["EvidenceVerdict"] | null;
                trigger?: ("own_history" | "peer" | "both") | null;
                week_from?: string | null;
                week_to?: string | null;
                min_own_deviation_pct?: number | null;
                min_peer_deviation_pct?: number | null;
                sort_by?: "week_of" | "route" | "route_type" | "cost_per_tonne_km" | "vs_own_history_pct" | "vs_similar_routes_pct" | "verdict";
                sort_order?: "asc" | "desc";
                limit?: number | null;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_AnomalyListData_"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Analysis unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_anomaly: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                route: string;
                week_of: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_AnomalyData_"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Analysis unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_route_timeline: {
        parameters: {
            query?: {
                week_from?: string | null;
                week_to?: string | null;
            };
            header?: never;
            path: {
                route: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_RouteTimelineData_"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Analysis unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_evaluation_report: {
        parameters: {
            query?: {
                include_checks?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_EvaluationReportData_"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Analysis unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_run_metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_RunMetricsData_"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Analysis unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
